### ISSUE TITLE
no output from blastValidate.pl

### ISSUE THREAD

**Issue by stephenturner** [bioforensics/blast-validate#2]
I'm running blastValidate.pl on the subway BA data exactly as specified in the readme. Getting some std error but no output either in the default filename or if I specify an output file.

All I get is some std err:

```
Loading taxonomy...
Read in blast output...
 start search with 8(bitwin), 0(len), (cov), (id), -64(eval)
done.
```

**Comment by adambazinet** [comment]
Hi Stephen,

Sorry about this! Some bugs in the script. Can you please update and try again?

thanks,
Adam

**Comment by stephenturner** [comment]
Looks to have fixed the issue, at least with my quick test on the subway data, thanks! FWIW, looks like you can no longer specify the output, that it always goes to fasta.params.lca. Thanks for fixing!

cc @kternus
